In [ ]:
#import libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score,classification_report,confusion_matrix

In [ ]:
#load the dataset
df=pd.read_csv('/content/Breast_Cancer - Breast_Cancer.csv')

In [ ]:
df.head()

,Age,Race,Marital Status,T Stage,N Stage,6th Stage,differentiate,Grade,A Stage,Tumor Size,Estrogen Status,Progesterone Status,Regional Node Examined,Reginol Node Positive,Survival Months,Status
0,68,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,4,Positive,Positive,24,1,60,Alive
1,50,White,Married,T2,N2,IIIA,Moderately differentiated,2,Regional,35,Positive,Positive,14,5,62,Alive
2,58,White,Divorced,T3,N3,IIIC,Moderately differentiated,2,Regional,63,Positive,Positive,14,7,75,Alive
3,58,White,Married,T1,N1,IIA,Poorly differentiated,3,Regional,18,Positive,Positive,2,1,84,Alive
4,47,White,Married,T2,N1,IIB,Poorly differentiated,3,Regional,41,Positive,Positive,3,1,50,Alive

In [ ]:
df.shape

(4024, 16)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4024 entries, 0 to 4023
Data columns (total 16 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Age                     4024 non-null   int64
 1   Race                    4024 non-null   object
 2   Marital Status          4024 non-null   object
 3   T Stage                 4024 non-null   object
 4   N Stage                 4024 non-null   object
 5   6th Stage               4024 non-null   object
 6   differentiate           4024 non-null   object
 7   Grade                   4024 non-null   object
 8   A Stage                 4024 non-null   object
 9   Tumor Size              4024 non-null   int64
 10  Estrogen Status         4024 non-null   object
 11  Progesterone Status     4024 non-null   object
 12  Regional Node Examined  4024 non-null   int64
 13  Reginol Node Positive   4024 non-null   int64
 14  Survival Months         4024 non-null   int64
 15  Status                  4024 non-null   object
dtypes: int64(5), object(11)
memory usage: 503.1+ KB

In [ ]:
df.describe()

,Age,Tumor Size,Regional Node Examined,Reginol Node Positive,Survival Months
count,4024.000000,4024.000000,4024.000000,4024.000000,4024.000000
mean,53.972167,30.473658,14.357107,4.158052,71.297962
std,8.963134,21.119696,8.099675,5.109331,22.921430
min,30.000000,1.000000,1.000000,1.000000,1.000000
25%,47.000000,16.000000,9.000000,1.000000,56.000000
50%,54.000000,25.000000,14.000000,2.000000,73.000000
75%,61.000000,38.000000,19.000000,5.000000,90.000000
max,69.000000,140.000000,61.000000,46.000000,107.000000

In [ ]:
# Numerical variables
numerical_cols = df.select_dtypes(include=['int64', 'float64']).columns
# Categorical variables
categorical_cols = df.select_dtypes(include=['object', 'category']).columns
print("Numerical Variables:")
print(list(numerical_cols))
print("\nCategorical Variables:")
print(list(categorical_cols))

Numerical Variables:
['Age', 'Tumor Size', 'Regional Node Examined', 'Reginol Node Positive', 'Survival Months']

Categorical Variables:
['Race', 'Marital Status', 'T Stage', 'N Stage', '6th Stage', 'differentiate', 'Grade', 'A Stage', 'Estrogen Status', 'Progesterone Status', 'Status']

In [ ]:
print("No of duplicated rows: ",df.duplicated().sum())

No of duplicated rows:  1

In [ ]:
df.drop_duplicates(inplace=True)

In [ ]:
print("No of duplicated rows: ",df.duplicated().sum())

No of duplicated rows:  0

In [ ]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
y = y.map({'Dead':0,'Alive':1})

In [ ]:
#split the data into training and testing
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
categorical_cols_x = x.select_dtypes(include=['object', 'category']).columns

In [ ]:
x_train = pd.get_dummies(x_train, columns=categorical_cols_x, drop_first=True)
x_test = pd.get_dummies(x_test, columns=categorical_cols_x, drop_first=True)
# Ensure that X_train and X_test have the same columns after one-hot encoding
x_train, x_test = x_train.align(x_test, join='outer', axis=1, fill_value=0)

In [ ]:
from sklearn.preprocessing import StandardScaler
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [ ]:
from sklearn.svm import LinearSVC
model=LinearSVC(random_state=42)
model.fit(x_train,y_train)

LinearSVC(random_state=42)

In [ ]:
y_pred = model.predict(x_test)
accuracy = accuracy_score(y_test, y_pred)
print("Accuracy:", accuracy)

Accuracy: 0.893167701863354

In [ ]:
#Evaluation metrics connfusion matrix,TP,FP,TN,FN
confusion_mat=confusion_matrix(y_test,y_pred)
print("Confusion Matrix:")
print(confusion_mat)

Confusion Matrix:
[[ 52  75]
 [ 11 667]]

In [ ]:
#classification report
classification_rep=classification_report(y_test,y_pred)
print("Classification Report:")
print(classification_rep)

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.41      0.55       127
           1       0.90      0.98      0.94       678

    accuracy                           0.89       805
   macro avg       0.86      0.70      0.74       805
weighted avg       0.89      0.89      0.88       805